views:
  - title: Home
    type: panel
    badges: []
    cards:
      - type: custom:sunsynk-power-flow-card
        panel_mode: true
        card_width: 53%
        large_font: true
        cardstyle: full
        show_solar: true
        card_height: 410px
        show_grid: true
        solar:
          mppts: 4
          display_mode: 2
          colour: orange
          show_daily: true
          animation_speed: 6
          max_power: 50000
          auto_scale: true
        inverter:
          modern: true
          colour: grey
          three_phase: false
          autarky: energy
          auto_scale: true
        battery:
          energy: 121000
          shutdown_soc: 30
          invert_power: false
          colour: green
          show_daily: true
          animation_speed: 6
          max_power: 50000
        load:
          colour: '#5fb6ad'
          show_daily: true
          show_aux: true
          animation_speed: 4
          max_power: 80000
          aux_name: AUX-Loads
          aux_colour:
            - 0
            - 238
            - 255
          aux_type: mdi:air-conditioner
          show_daily_aux: true
          invert_aux: false
          show_absolute_aux: false
          aux_off_colour:
            - 208
            - 205
            - 205
          dynamic_icon: true
          dynamic_colour: true
        grid:
          colour: '#5490c2'
          show_daily_buy: true
          show_daily_sell: false
          no_grid_colour: red
          show_nonessential: false
          animation_speed: 9
          max_power: 60000
          grid_name: Generator
          nonessential_icon: mdi:generator-mobile
          nonessential_name: Generator
        entities:
          use_timer_248: switch.deyeinvertermaster_time_of_use
          priority_load_243: sensor.deyeinvertermaster_priority_charge_or_load
          day_battery_charge_70: sensor.deyeinvertermaster_summary_day_battery_charge
          day_battery_discharge_71: sensor.deyeinvertermaster_summary_day_battery_discharge
          day_load_energy_84: sensor.deyeinvertermaster_summary_day_load
          day_grid_import_76: sensor.deyeinvertermaster_summary_day_grid_import_buy
          day_grid_export_77: sensor.deyeinvertermaster_summary_day_grid_export_sell
          day_pv_energy_108: sensor.deyeinvertermaster_summary_day_pv
          inverter_voltage_154: sensor.deyeinvertermaster_grid_voltage_l1
          load_frequency_192: sensor.deyeinvertermaster_grid_frequency
          inverter_current_164: sensor.deyeinvertermaster_inverter_output_current_l1
          inverter_power_175: sensor.deyeinvertermaster_inverter_output_power
          grid_power_169: sensor.deyeinvertermaster_grid_load
          radiator_temp_91: sensor.deyeinvertermaster_temperature_ac_transformer
          dc_transformer_temp_90: sensor.deyeinvertermaster_temperature_dc_transformer
          pv1_power_186: sensor.deyeinvertermaster_pv1_power
          pv2_power_187: sensor.deyeinvertermaster_pv2_power
          pv3_power_188: sensor.deyeinvertermaster_pv3_power
          pv4_power_189: sensor.deyeinvertermaster_pv4_power
          battery_voltage_183: sensor.deyeinvertermaster_battery_voltage
          battery_soc_184: sensor.deyeinvertermaster_battery_soc
          battery_power_190: sensor.deyeinvertermaster_battery_output_power
          battery_current_191: sensor.deyeinvertermaster_battery_output_current
          battery_temp_182: sensor.deyeinvertermaster_battery_temperature
          grid_ct_power_172: sensor.deyeinvertermaster_grid_power_ct_clamp
          pv1_voltage_109: sensor.deyeinvertermaster_pv1_voltage
          pv1_current_110: sensor.deyeinvertermaster_pv1_current
          pv2_voltage_111: sensor.deyeinvertermaster_pv2_voltage
          pv2_current_112: sensor.deyeinvertermaster_pv2_current
          pv3_voltage_113: sensor.deyeinvertermaster_pv3_voltage
          pv3_current_114: sensor.deyeinvertermaster_pv3_current
          pv4_voltage_115: sensor.deyeinvertermaster_pv4_voltage
          pv4_current_116: sensor.deyeinvertermaster_pv4_current
          grid_connected_status_194: binary_sensor.deyeinvertermaster_grid_connected_status
          inverter_status_59: sensor.deyeinvertercmaster_inverter_system_state
          aux_power_166: sensor.deyeinvertermaster_generator_port_power
          day_aux_energy: sensor.deyeinvertermaster_summary_day_generator
          remaining_solar: sensor.energy_production_today_remaining
          solar_sell_247: switch.deyeinvertermaster_export_solar_enabled
        decimal_places: 2
        show_battery: true


