sensor:
  - name: "deyeinvertermaster_solar_power_used"
    state: "{{ (states('sensor.deyeinvertermaster_summary_day_pv') | float(0) - states('sensor.deyeinvertermaster_summary_day_battery_charge') | float(0)) |round(1) }}"
    unit_of_measurement: "kWh"
    device_class: energy

  - name: "deyeinvertermaster_essential_load"
    state: "{{ (states('sensor.deyeinvertermaster_inverter_output_power') |float(0)  + (states('sensor.deyeinvertermaster_grid_load') |float(0) - states('sensor.deyeinvertermaster_aux_output_power') |float(0) )) | round(0)}}"
    unit_of_measurement: "W"
    device_class: power

  - name: "deyeinvertermaster_non_essential_load"
    state: "{{ (states('sensor.deyeinvertermaster_grid_external_power') |float(0)  - (states('sensor.deyeinvertermaster_grid_load') |float(0))) | round(0)}}"
    unit_of_measurement: "W"
    device_class: power

  - name: "deyeinvertermaster_priority_charge_or_load"
    state: |
      {% if is_state('select.deyeinvertermaster_energy_management_model', 'Battery Priority Mode') %}
        off
      {% else %}
        on
      {% endif %}
