- id: '1717429630744'
  alias: Prepaid meter recharge
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_number.prepaid_meter_units
  condition:
  - condition: template
    value_template: '{{ states(''input_number.prepaid_meter_units'') | float > 0 }}'
  actions:
  - action: input_number.set_value
    metadata: {}
    data:
      value: '{{ ((states(''sensor.deyeinvertermaster_summary_total_grid_import_buy'') |
        float(6))  * 1000.0) }}'
    target:
      entity_id: input_number.prepaid_meter_inverter_total_units
  mode: single
